[package]
name = "devcon"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.41", features = ["derive"] }
config = { version = "0.15.13", features = ["yaml"] }
crossterm = "0.29.0"
ratatui = "0.29.0"
ratatui-widgets = "0.2.2"
serde = "1.0.219"
serde_yaml = "0.9.34"
xdg = "3.0.0"
urlencoding = "2.1"

[dev-dependencies]
tempfile = "3.8"
