[package]
name = "devcon-proto"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
prost = "0.14.3"
bytes = "1.11.1"

[build-dependencies]
prost-build = "0.14.3"
