[package]
name = "devcon-agent"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
devcon-proto = { path = "../proto" }
prost = "0.13"
bytes = "1.9"
clap = { version = "4.5", features = ["derive"] }

[[bin]]
name = "devcon-agent"
path = "src/main.rs"
